version: '3'
services:
  node:
    restart: always
    build: .
    ports: 
      - "3005:3005"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3006:8081